### ISSUE TITLE
Android Layout variations

### ISSUE THREAD

**Issue by polenchheang** [JetBrains/anko#10]
I would like to know, how to use anko to handle android layout variations like layout-land or layout-sw600dp?
It would great if you can provide sample code.

**Comment by yanex** [comment]
It is simple.

```kotlin
textView(if (configuration.portrait) "Portrait" else "Landscape")
textView(if (displayMetrics.densityDpi == XHDPI) "Xhdpi" else "Non-xhdpi")
```

**Comment by polenchheang** [comment]
I get your idea, thanks you!

**Comment by evant** [comment]
Would be nice if there was a little sugar around this, as it can get a bit verbose for more configuration combinations. I really like android's resource selection in this regard. Could you create something like this (bikesheading on the syntax, I haven't thought too much about it)
```kotlin
configurations {
  on("land") {
    textView("Landscape")
  }
  on("sw600dp-v17") {
    textView("On api 17+ tablets")
  }
}
```
and it would pick the best one based on the same algorithm as described [here](http://developer.android.com/guide/topics/resources/providing-resources.html#BestMatch).

**Comment by yanex** [comment]
That's a good idea, thank you!
I can't say now if the string description like `"sw600dp-v17"` would be safe enough cause we have to throw Exceptions on runtime it argument has an invalid format, but it's definitely worth considering.

**Comment by evant** [comment]
you could do something like `on(orientaion = LANDSCAPE)` or `on(sw = dip(600), version = 17)` instead if you want more type safety, you have a trade off of a bit of verboseness though.

**Comment by EddieRingle** [comment]
I really like @evant's proposal. I particularly don't have an issue with the extra verbosity of the type-safe configuration parameters; in fact, I think I prefer them to strings.

**Comment by evant** [comment]
I actually have an implementation of the resource selection algorithm if that would help things. It works directly on the qualifier strings instead of a collection of qualifiers, so it would have to be modified a bit if you want to go with the more typesafe route (which the more I think about it, the more I like as well)
https://github.com/willowtreeapps/resPeeker/blob/master/resPeeker-idea/src/com/willowtreeapps/respeeker/idea/res/ResourceFinder.java

**Comment by EddieRingle** [comment]
@yanex This can probably be closed now that the configuration DSL is in, right?
