### ISSUE TITLE
Anko DSL Preview Plugin Android Studio 1.5 preview 2 NoClassDefFoundError

### ISSUE THREAD

**Issue by tagantroy** [JetBrains/anko#101]
11:03:43 NoClassDefFoundError: org/jetbrains/kotlin/psi/JetClass
11:03:50 NoClassDefFoundError: org/jetbrains/kotlin/psi/JetExpression
11:03:55 NoClassDefFoundError: org/jetbrains/kotlin/psi/JetExpression
 
Android Studio: 141.2343905
Anko DSL Preview 0.7.1
Kotlin: 1.0.0-beta-1038-IJ141-17

not working syntax highlighting + all anko dsl code highlighted red

**Comment by Ribesg** [comment]
Anko 0.7.1 is for Kotlin M14.
You want Anko 0.7.2.

**Comment by yole** [comment]
Indeed, you need to install a new version of Anko.

**Comment by tagantroy** [comment]
Last version of Anko DSL Preview plugin - 0.7.1 updated 02.10.15

**Comment by yanex** [comment]
Anko DSL Preview plugin was updated just now. Sorry for the inconvenience!
