### ISSUE TITLE
AnkoLogger version 0.7.2 works with info level only

### ISSUE THREAD

**Issue by maomaobug** [JetBrains/anko#104]
I have tried with android.util.Log and it works perfectly on my Android Studio, but with AnkoLogger, it works with info level only. I have never changed any configuration of my IDE.

**Comment by yanex** [comment]
`AnkoLogger` uses `Log.isLoggable()` under the hood which ignores `VERBOSE` and `DEBUG` log levels by default.
You can read more about it here: https://mobiarch.wordpress.com/2012/05/11/proper-logging-from-android-application/.

**Comment by dcalano** [comment]
This is a pretty poor design choice imo. There is no need for the extra effort just to get a statement to print to logcat...

**Comment by jonmcclung** [comment]
@hendrawd It seems the way to enable the log is to do the following:

```
$ adb shell
$ setprop  log.tag.TAG  VERBOSE
```
where `TAG` is any tag you want to see (This is probably the name of the class doing the logging.)
