### ISSUE TITLE
INSTALL_FAILED_DEXOPT on Android emulators 4.0.3 - 4.4.4

### ISSUE THREAD

**Issue by mykhailo-gaidai** [JetBrains/anko#108]
Adding `compile 'org.jetbrains.anko:anko-sdk15:0.7.2'` to dependencies starts producing INSTALL_FAILED_DEXOPT when installing on Android emulators(native and genymotion): 
* 4.0.3(API 15)
* 4.1.1(API 16) 
* 4.2.2(API 17)
* 4.3(API 18)

4.4.4(19) works fine

kotlin 1.0.0-beta-1103

**Comment by yanex** [comment]
Please use [Anko 0.7.3](https://github.com/JetBrains/anko/releases/tag/v0.7.3).
