### ISSUE TITLE
set[Property]Size with a dimension resource

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/anko#11]
For each size, there should be an easy way to set a resource dimension.

Also, when setting a text size from a resource dimension, COMPLEX_UNIT_PX must be passed.

As an example, here's my extension method to TextView to set a textSize from a dimension resource:

```kotlin
public var TextView.textSizeDimen: Int
    get() = throw AnkoException("'textSizeDimen' property doesn't have a getter")
    set(res) = setTextSize(TypedValue.COMPLEX_UNIT_PX, getContext().getResources().getDimension(res))
```

**Comment by yanex** [comment]
Sounds reasonable. `TextView.textSize` is a kind of special attribute (it accepts `sp` float instead of `px` Int, thus has different semantics).
For any other attributes, `dim(R.dimen.<id>)` function (doesn't exist yet but in the plans) should be enough.

**Comment by yanex** [comment]
Fixed.
