### ISSUE TITLE
Use of getTag for listeners with multiple functions

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/anko#12]
For things like `TextView.addTextChangedListener`, Anko has three diferent functions: `beforeTextChanged`, `onTextChanged` and `afterTextChanged`.

Each of these three functions all start with:
```kotlin
val props = getTag() as? ViewProps
if (props != null) {
  /* do some magic */
}
```

...which means that those callback setters will only work if the view tag is set to a `ViewProps` object. This in turn means that the setter will *not work* in any of those cases:

1. The programmer calls `setTag(Object)` inside the init block before calling any of those three functions.
2. The programmer calls any of these three function on a view that was created either manually or through an inflated XML.

Moreover, these functions will **fail silently**, meaning that it will not work and the programmer will have very little way of *understanding why*.

Here is a utility that I have created that essentially does the same, but without those problems (in fact, I was using these kind of utils before Anko):

```kotlin
class TextWatcherFunctions : TextWatcher {
    private var _beforeTextChanged: ((CharSequence, Int, Int, Int) -> Unit)? = null
    private var _onTextChanged: ((CharSequence, Int, Int, Int) -> Unit)? = null
    private var _afterTextChanged: ((Editable) -> Unit)? = null

    override fun beforeTextChanged(s: CharSequence, start: Int, count: Int, after: Int)
            = _beforeTextChanged?.invoke(s, start, count, after)

    override fun onTextChanged(s: CharSequence, start: Int, before: Int, count: Int)
            = _onTextChanged?.invoke(s, start, before, count)

    override fun afterTextChanged(s: Editable)
            = _afterTextChanged?.invoke(s)

    public fun beforeTextChanged(function: (CharSequence, Int, Int, Int) -> Unit) {
        _beforeTextChanged = function
    }

    public fun onTextChanged(function: (CharSequence, Int, Int, Int) -> Unit) {
        _onTextChanged = function
    }

    public fun afterTextChanged(function: (Editable) -> Unit) {
        _afterTextChanged = function
    }
}

public fun EditText.addTextChangedListener(init: TextWatcherFunctions.() -> Unit): TextWatcher {
    val watcher = TextWatcherFunctions()
    watcher.init()
    addTextChangedListener(watcher)
    return watcher
}
```

This allows me to set only one of those functions with the syntax:
```kotlin
myEditText.addTextChangedListener {
    onTextChanged { /* Do something amazing :) */ }
}
```

In the context of Anko, instead of
```kotlin
editText {
    onTextChanged { /* Do something amazing :) */ }
}
```
it would be:
```kotlin
editText {
    addTextChangedListener {
        onTextChanged { /* Do something amazing :) */ }
    }
}
```
Of course, the wording would have to be re-thought to be closer to Anko's paradigm.

I know this adds a new block level, but I argue that this has significant advantages over the current implementation:

1. It does not prevent the programmer from using tags
2. It does not fail silently
3. It is compatible both inside and outside Anko's building DSL
4. The function `addTextChangedListener` returns the created listener, allowing the programmer to later call `removeTextChangedListener`. Although, to be complete, it would be cleaner for it to return an rxjava like `Subscription` object on which to call an `unsubscribe`.
5. It is closer to Android, and IMHO, easier for Android Java programmers to understand.

What do you think ?

**Comment by yanex** [comment]
I really like this. Indeed, it requires an additional block level, but, among all other benefits, it goes well with auto-completion in IDE.

**Comment by yanex** [comment]
Fixed.
