### ISSUE TITLE
Context.uiThread is private

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/anko#13]
`Activity` has `runOnUIThread {}` but
- A `Fragment` must call `getActivity().runOnUiThread {}`
- A `Service` must call `Handler(Looper.getMainLooper()).post {}`

Anko has a `Context.uiThread` method but it is private and only meant to be used for Async contexts through `AnkoAsyncContext.uiThread`.

It would be great to give all Android system component their own `uiThread {}` method.

**Comment by yanex** [comment]
Done.
