### ISSUE TITLE
Problem with Intent and missing anko's startActivityForResult

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/anko#15]
I found 2 problems with the `Intent` function:

1. It collides with `android.content.Intent`, making it difficult to use if I'm in an activity that overrides functions like `onActivityResult` or `onNewIntent`. Since `Activity` already has a property `intent`, I propose to rename the function to `intentFor` or `newIntent`.

2. When I use it, I get an error: "Type argument is not within its bound. Expected: java.lang.class<*>. Found: com.my.MyActivity". When I ctrl+click on it, I get the signature of the function with the type parameter being `reified T : java.lang.Class<*>`. I guess it should only be `reified T : Any`.

Also, Anko provides a utility function `startActivity` but not `startActivityForResult`.

Finally, `startActivity` is defined for `Activity` and `android.app.Fragment` but not for `android.support.v4.app.Fragment`

**Comment by yanex** [comment]
Fixed.

**Comment by KosratDAhmad** [comment]
The last part of the question is not solved 

> Finally, startActivity is defined for Activity and android.app.Fragment but not for android.support.v4.app.Fragment

**Comment by 4u7** [comment]
Contributions are welcome!
