### ISSUE TITLE
DSL Preview plugin: unable to see the layout preview

### ISSUE THREAD

**Issue by Pianco** [JetBrains/anko#18]
Hi! I'm trying to use the DLS Preview plugin in Android Studio. However, it show only the white background, not the preview, even when I use the refresh button. How to fix this?

**Comment by yanex** [comment]
What is a superclass of your Activity?

**Comment by Pianco** [comment]
I've tried using a subclass of Fragment.

**Comment by yanex** [comment]
Duplicated by #33.
