### ISSUE TITLE
intentFor parameters and documentation

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/anko#30]
First of all, the [documentation](https://github.com/JetBrains/anko/blob/master/doc/ADVANCED.md#intents) should be updated to reflect the renaming of the function `Intent` to `intentFor`.

The documentation states that parameters can be given to `Intent`, but the function `intentFor` does not take any parameter.

Just like the function `startActivity`, I believe it should take `vararg params: Pair<String, Any>` as parameter.

**Comment by yanex** [comment]
Fixed. Thank you!
