### ISSUE TITLE
Missing version 0.6-19s in JCenter

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/anko#32]
As you can see [here](https://jcenter.bintray.com/org/jetbrains/anko/anko/), the Anko JCenter repository contains versions `0.6-15`, `0.6-15s` and `0.6-19` but no `0.6-19s`.
So we can't have both the SDK 19 features *and* the support library.

**Comment by yanex** [comment]
`0.6-19s` is present in `jcenter` repository: https://bintray.com/jetbrains/anko/anko/0.6-19s/view#files.

**Comment by yanex** [comment]
It was a BinTray issue, and now it should be fixed.

**Comment by SalomonBrys** [comment]
Confirmed. Thanks a lot ;)
