### ISSUE TITLE
Support v7 tinting

### ISSUE THREAD

**Issue by yoavst** [JetBrains/anko#35]
It looks like the default support v7 appcompat tinting is disabled if you use anko.
Is there any solution other than adding those?
```kotlin
public fun ViewManager.appCompatEditText(init: AppCompatEditText.() -> Unit = {}): AppCompatEditText =
        __dslAddView({ AppCompatEditText(it, null) }, init, this)

public fun ViewManager.appCompatCheckBox(init: AppCompatCheckBox.() -> Unit = {}): AppCompatCheckBox =
        __dslAddView({ AppCompatCheckBox(it, null) }, init, this)

public fun ViewManager.appCompatRadioButton(init: AppCompatRadioButton.() -> Unit = {}): AppCompatRadioButton =
        __dslAddView({ AppCompatRadioButton(it, null) }, init, this)
```

**Comment by yanex** [comment]
This feature is currently under the development.

The first (more obvious and straightforward) way is to add some functions like `editTextCompat()` which will add `AppCompatEditText` if the Android SDK version < 21.
The other way is to modify standard functions (`button()`, `editText()`) and so on so they produce tinted Views seamlessly.

The preferred way is the first: one always knows what he is doing, and it requires no modifications in versions without an `appcompat-v7` library.

**Comment by schwiz** [comment]
I disagree, the first way does not sound better. You don't need to update your code to replace EditText with AppCompatEditText when using java or something other than anko. So requiring that for anko is not preferable. 

I think the solution to the original question is to use View.inflate rather than the constructor.

**Comment by yanex** [comment]
Done.

**Comment by schwiz** [comment]
@yanex looking thorough the source of org.jetbrains.anko:anko:0.6.3-19s I'm not seeing anything to indicate this is fixed. For example, the below code for tintedEditText is still using the wrong constructor.  Tinting will not work unless the constructor taking an AttributeSet is used. 

```kotlin
public inline fun ViewManager.tintedEditText(inlineOptions(InlineOption.ONLY_LOCAL_RETURN) init: EditText.() -> Unit): EditText = addView<EditText> {
    ctx ->
    val view = if (Build.VERSION.SDK_INT < 21)
        android.support.v7.widget.AppCompatEditText(ctx)
    else
        EditText(ctx)

    view.init()
    view
}
```
