### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by stephanenicolas** [JetBrains/anko#43]
Can you achieve the performances of an annotation processor with Anko ?

**Comment by yanex** [comment]
Nobody made the detailed Anko/XML performance test yet.
Though, Anko does not need to parse binary XML layouts and all widgets are basically created without using Java Reflection (unless you explicitly use `customView()` or `include()`), so, probably, Anko is a bit faster than XML.

**Comment by yanex** [comment]
**Update:**

Some comparisons:
- https://android.jlelse.eu/400-faster-layouts-with-anko-da17f32c45dd
- https://nethergrim.github.io/performance/2016/04/16/anko.html
