### ISSUE TITLE
SingleColumnParser/ScalarColumnParser: wrong precondition

### ISSUE THREAD

**Issue by Gubbel** [JetBrains/anko#45]
Both `parseRow()` methods throw an exception if the column count is `!= 0` instead of when it is `!= 1`:

<pre>override fun parseRow(columns: Array<Any>): T {
    if (<b>columns.size() != 0</b>)
        throw SQLiteException("Invalid row: row for SingleColumnParser must contain exactly one column")
    [suppress("UNCHECKED_CAST")]
    return columns[0] as T
}</pre>

**Comment by yanex** [comment]
Fixed. Thank you!
