### ISSUE TITLE
Suggestion for using 10.dip or 10.dp

### ISSUE THREAD

**Issue by foobnix** [JetBrains/anko#47]
fun dipToPx(dp: Int): Int {
    return dp * Resources.getSystem().getDisplayMetrics().density.toInt()
}

val Int.px: Int
    get(){
        return this
    }

val Int.dp: Int
    get(){
        return dipToPx(this);
    }
val Int.dip: Int
    get(){
        return dipToPx(this)
    }

**Comment by foobnix** [comment]
also add the same behavior for sp, px etc
    val Int.dp:Int
        get(){
            return dip(this)
        }

  verticalLayout(){
            padding = 15.dp
....
}

I think this code read much better

**Comment by yanex** [comment]
According to [Resources](http://developer.android.com/reference/android/content/res/Resources.html#getSystem()),

> Return a global shared Resources object that provides access to only system resources (no application resources), and is not configured for the current screen (can not use dimension units, does not change based on orientation, etc).
