### ISSUE TITLE
Seperate DSL library from Utility functions

### ISSUE THREAD

**Issue by danijoo** [JetBrains/anko#58]
Hi,

Im not a big fan of the ank DSL style but the extension functions are really awesome. If would be nice if you could split the two libraries and make it possible to only include the extension functions in projects.

**Comment by yanex** [comment]
Yes, it is in the plans.

**Comment by yanex** [comment]
It will be supported in Anko just after all the changes described [here](http://blog.jetbrains.com/kotlin/2015/06/improving-java-interop-top-level-functions-and-properties/) will take place.

**Comment by danijoo** [comment]
any news on this?

**Comment by Ribesg** [comment]
Isn't this done? If you just use `org.jetbrains.anko:anko-common`?
