### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by colriot** [JetBrains/anko#61]
It would be useful to add CHANGELOG.md file to enable quick sync with library changes for its users. Parsing commit log trying to filter essential changes is rather troublesome.

**Comment by yanex** [comment]
You can find all changes for a particular release in the [Releases](https://github.com/JetBrains/anko/releases) page.

**Comment by colriot** [comment]
Aha! Well, if you don't mind, I'll create `CHANGELOG.md` based on Releases page. It's common practice and it's independent from GitHub.

**Comment by yanex** [comment]
Yes, it would be good! :)
