### ISSUE TITLE
No static method async(Landroid/support/v4/app/Fragment;Lkotlin/jvm/functions/Function1;)Ljava/util/concurrent/Future; in class Lorg/jetbrains/anko/AnkoPackage; or its super classes (declaration of 'org.jetbrains.anko.AnkoPackage'

### ISSUE THREAD

**Issue by cypressious** [JetBrains/anko#64]
I'm using `asyncResult` in one of my fragments and when I execute it the following exception occurs:

> java.lang.NoSuchMethodError: No static method async(Landroid/support/v4/app/Fragment;Lkotlin/jvm/functions/Function1;)Ljava/util/concurrent/Future; in class Lorg/jetbrains/anko/AnkoPackage; or its super classes (declaration of 'org.jetbrains.anko.AnkoPackage' appears in /data/app/pacakge.name/base.apk)

Also when compiling with ProGuard enabled the following warning appears:

> Warning: de.busliniensuche.android.BookingSummaryServiceFragment: can't find referenced method 'java.util.concurrent.Future asyncResult(android.content.Context,kotlin.jvm.functions.Function0)' in program class org.jetbrains.anko.AnkoPackage

I'm using Anko 0.6.2-19s and Kotlin 0.12.412 with Gradle.

**Comment by pTalanov** [comment]
Hello. Can't say about anko. This problem may arise if you add top level member (property or function) to that package (org.jetbrains.anko). If you're not doing anything of the sort, disregard my comment.

**Comment by cypressious** [comment]
That was it! Thanks for the help.
