### ISSUE TITLE
How to override AnkoLogger tag

### ISSUE THREAD

**Issue by schwiz** [JetBrains/anko#65]
When I try to override the log tag I get an IllegalAccessError. What am I doing wrong? 

abstract class BaseActivity : RxAppCompatActivity(), AnkoLogger by KoatLogger(){

}

//... off in some other file
class KoatLogger : AnkoLogger {
    override val loggerTag = "koat"
}

**Comment by yanex** [comment]
Related Kotlin issue: https://youtrack.jetbrains.com/issue/KT-4250

**Comment by schwiz** [comment]
When will this be released to jcenter and what version will it be in?

**Comment by yanex** [comment]
The bug is fixed since at least Kotlin 1.0.1.
