### ISSUE TITLE
Layout param scope issue

### ISSUE THREAD

**Issue by schwiz** [JetBrains/anko#69]
Trying to nest two views that don't want default layout params doesn't work correctly due to scope.  In the example below you get a runtime error because `verticalLayout{}.layoutParams()` tries to invoke the ScrollView layoutParams instead of LineraLayout.  The workaround is to do this `verticalLayout{layoutParams()}` but in that case margins do not work.

```
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
            root = verticalLayout {
                toolbar = toolbarSupport {
                    defaultToolbar()
                    title = getLabel()
                }
                scrollView = scrollView{
                    ll = verticalLayout{

                    }.layoutParams(width = matchParent)

                }.layoutParams(matchParent, matchParent)
            }
```

**Comment by yanex** [comment]
Maybe you are talking about [this](https://github.com/JetBrains/anko/issues/54) bug?
It is fixed, though now it is only in the `master` branch. Artefacts from `master` branch can be downloaded [here](https://teamcity.jetbrains.com/viewType.html?buildTypeId=ProjectsWrittenInKotlin_Anko&branch_ProjectsWrittenInKotlin=%3Cdefault%3E&tab=buildTypeStatusDiv).

**Comment by schwiz** [comment]
I think that is the issue I was having! The link you gave me requires a login though.

**Comment by yanex** [comment]
You can log in as guest.
