### ISSUE TITLE
AnkoLogger error throwable param

### ISSUE THREAD

**Issue by schwiz** [JetBrains/anko#70]
AnkoLogger.error() needs a default throwable param so you can make the call Log.e(String, String, Throwable) to print a stacktrace.

**Comment by yanex** [comment]
Is it really needed?
You can always call `e.printStackTrace()` in such cases.

**Comment by schwiz** [comment]
Yes I use this api all of the time. `e.printStackTrace()` doesn't put your tag on the stacktrace. Also, the lazy lambdas are nice to have.

**Comment by yanex** [comment]
Oh, I understood, you are talking about http://developer.android.com/reference/android/util/Log.html#e(java.lang.String,%20java.lang.String,%20java.lang.Throwable).

It will be supported in next versions.

**Comment by yanex** [comment]
Fixed in 017494b7e7b4c4a72af44a7ba309e5162566eeb0.

**Comment by schwiz** [comment]
It should just be on the error methods

**Comment by schwiz** [comment]
Any ETA on maven release?

**Comment by yanex** [comment]
@schwiz All artefacts should be available in jcenter.
