### ISSUE TITLE
Kotlin M13

### ISSUE THREAD

**Issue by yanex** [JetBrains/anko#82]

**Comment by alexustinovsm** [comment]
It doesn't work for 0.13.1513! I have to rollback to M12

**Comment by yanex** [comment]
New version will be available today.

**Comment by tmiyamon** [comment]
I'm waiting for the release!

**Comment by cypressious** [comment]
@yanex Could you please take a look at https://github.com/JetBrains/anko/issues/78 before releasing? asyncResult is basicly useless now.

**Comment by mboudraa** [comment]
@yanex Will it still be released today ?

**Comment by yanex** [comment]
Done. https://github.com/JetBrains/anko/releases/tag/v0.7
