### ISSUE TITLE
M13 and layoutParams

### ISSUE THREAD

**Issue by jupl** [JetBrains/anko#88]
Given that one of the features in M13 is "Java get/set pairs are now seen as properties in Kotlin" `layoutParams` as in the example below and in the README no longer works since it is referencing `getLayoutParams`/`setLayoutParams` instead.

```kotlin
linearLayout {
    button("Login") {
        textSize = 26f
    }.layoutParams(width = wrapContent) {
        horizontalMargin = dip(5)
        topMargin = dip(10)
    }
}
```

**Comment by Ribesg** [comment]
It has been renamed to lparams. (See https://github.com/JetBrains/anko/commit/246ad696babbd044626b27853f8677647c68bf2c)

**Comment by jupl** [comment]
Hmm. I'm not getting `lparams` as an option in Android Studio. I'm currently using `org.jetbrains.anko:anko-sdk15:0.7`.
