### ISSUE TITLE
Update to Kotlin M14

### ISSUE THREAD

**Issue by Ribesg** [JetBrains/anko#90]
The update seems to be done, but the 0.7.1 artifacts cannot be resolved.
They may not be uploaded yet.

**Comment by Ribesg** [comment]
All the libs I depend on are now available, I guess it's done :)

**Comment by yanex** [comment]
Anko 0.7.1 is released https://github.com/JetBrains/anko/releases/tag/v0.7.1.

**Comment by Ribesg** [comment]
It was not entirely available on jcenter until 10 minutes ago for some reasons.
