### ISSUE TITLE
Kotlin 1.0 Beta Candidate support

### ISSUE THREAD

**Issue by clemp6r** [JetBrains/anko#98]
Please update Anko for Kotlin 1.0 Beta Candidate.

http://blog.jetbrains.com/kotlin/2015/10/kotlin-1-0-beta-candidate-is-out/

**Comment by Ribesg** [comment]
+1

**Comment by yanex** [comment]
Anko 0.7.2. is out: https://github.com/JetBrains/anko/releases/tag/v0.7.2.

**Comment by kamoljan** [comment]
@yaegor thank you!

**Comment by clemp6r** [comment]
With anko 0.7.2 and Kotlin 1.0.0-beta-1038 I got the following error (proguard enabled)

```
Warning: org.jetbrains.anko.ContextUtilsKt__ContextUtilsKt: can't find referenced method 'void reifySafeCheckcast(java.lang.String)' in program class kotlin.jvm.internal.Intrinsics
Warning: org.jetbrains.anko.support.v4.SupportKt__SupportKt: can't find referenced method 'void reifySafeCheckcast(java.lang.String)' in program class kotlin.jvm.internal.Intrinsics
```

**Comment by clemp6r** [comment]
I think we might reopen the issue as it seems there is a compatibility problem between the released version of anko 0.7.2 and Kotlin 1.0.0 beta.

**Comment by Ribesg** [comment]
Well I don't get this error.

**Comment by clemp6r** [comment]
Do you use ProGuard?

**Comment by Ribesg** [comment]
No (or I should say not yet), it may be the cause. Try to disable it to confirm.

**Comment by clemp6r** [comment]
I can't (because of the 65k methods limit).

**Comment by dslysenko** [comment]
+1, I still get this error with Kotlin version 1.0.0-beta-3594, gradle 2.8, and the following anko dependencies in build.gradle:

    compile 'org.jetbrains.anko:anko-sdk15:0.8'
    compile 'org.jetbrains.anko:anko-appcompat-v7:0.8' // For appcompat-v7 bindings

The dontwarn silenced this error, but I'd still like to see an official response if possible.
